---
- name: Generate config files
  template: src=access_switch.j2 dest=/home/pmusolino/Network-Automation-with-Python-and-Ansible-class/week5/configs/{{item.hostname}}.txt
  with_items: access_switches
